services:
  - type: web
    name: kitaab-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install && cd ../Frontend && npm install && npm run build
    startCommand: cd Backend && npm install && node app.js
    envVars:
      - key: NODE_ENV
        value: production
